### ISSUE TITLE
Using extension - security

### ISSUE THREAD

**Issue by ahmed-babic** [JoostVoskuil/azure-devops-gitleaks#1]
Hi,

I'm interested in security aspect of this extension. Is it exposing code anywhere else - external service or it is only maintained within my instance - agent where I am executing the job?
As I understood it only downloads tool and runs it like I could do manually on my own desktop instance.

Thank you!

**Comment by JoostVoskuil** [comment]
Hi Ahmed,

It is not exposing the code anywhere else. In your pipeline the checkout of the code happens and the extension will pass that location to gitleaks.

You are right. Gitleaks is downloaded from github, that's it. All runs on your hosted or private agents like all other jobs
