### ISSUE TITLE
Gitleaks not scanning Readme.md and yaml files for secrets in in ADO GitLeaks task.

### ISSUE THREAD

**Issue by sindhujarudra** [JoostVoskuil/azure-devops-gitleaks#31]
Describe the bug
I have gitleaks extension installed on my AzureDevops. I have added the stage in my yaml file for repo to detect the secrets.
Repo has different file types with hardcoded secrets ( AZURE PAT tokens).

.ps1
cs
yml
Readme.md
5.json
When I run my pipeline, it detects the secrets in .json/cs/.ps1 files and it is ignoring Readme.md/yml files. Is this expected.
I have attached screenshots of the logs and the sample yml file with hardcoded PAT token.

To Reproduce
Create a repo with above file extensions with some secrets and run the AzureDevops pipeline.

Expected behavior
It should detect the secrets in the yml and Readme.md files.

Code: 
```- task: Gitleaks@2
            inputs:
              scanlocation: '$(Build.SourcesDirectory)'
              configtype: 'predefined'
              predefinedconfigfile: 'GitleaksUdmCombo.toml'
              reportformat: 'sarif'
              verbose: true
            displayName: "Gitleaks Credential Scanner"
  ```

Screenshots
![image](https://user-images.githubusercontent.com/46533139/150809515-112f84c3-d6b9-4880-b9a7-25093606aae9.png)

![image](https://user-images.githubusercontent.com/46533139/150809558-6ab5cf57-9e98-434c-9306-023946f3785d.png)

Thanks !!

@JoostVoskuil

**Comment by JoostVoskuil** [comment]
Hi @sindhujarudra can you retest this? It should detect in yml files now but in MD files this is hard, because of the quotes should be there.

**Comment by sindhujarudra** [comment]
@JoostVoskuil  It worked.. Thanks!!
