### ISSUE TITLE
Warning message during Gitleaks scan on pull requests

### ISSUE THREAD

**Issue by rrudduck** [JoostVoskuil/azure-devops-gitleaks#33]
We recently started receiving this warning when gitleaks runs during PR builds.

**_##[warning]For prevalidation/smart scanning mode, only 'Git' is supported as repository type. This repository type is 'TfsGit'_**

I believe it might be related to the changes from earlier today: https://github.com/JoostVoskuil/azure-devops-gitleaks/pull/32

Is there an additional option we need to set or is this a bug in the extension?

**Comment by JoostVoskuil** [comment]
Hi @rrudduck sorry this is my mistake (never work on this when you are tired ;))
Can you check if the issue is solved? Thank you

**Comment by rrudduck** [comment]
It looks good - thank you!
