### ISSUE TITLE
CSV reports to be able to save with specific path/file name

### ISSUE THREAD

**Issue by martindz** [JoostVoskuil/azure-devops-gitleaks#36]
At the moment it looks like extension doesn't support to specify the name for file published in the Azure Devops artifacts. 

It looks like follows 
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/38648254/152812523-0eeaf392-d93d-491d-ba30-5947776fcba1.png">

`<Standard name> <some guid>.csv `
There is requirement to have specifi name for every file. Is it possible to provide variable value to fill the name?

**Comment by JoostVoskuil** [comment]
HI @martindz I will have a look at it. It is not so easy as you might think because of the retry stage/job mechanism.

**Comment by martindz** [comment]
We use the approach with Cred Scanner and looking for similar functionality. We run Cred scanner centrally against all projects and repos, later on we provided visualization through Powerbi.

**Comment by JoostVoskuil** [comment]
Added the option to specify custom report names
