### ISSUE TITLE
Gitleaks scans don't scan all folders and files in Repo

### ISSUE THREAD

**Issue by Sageatahan** [JoostVoskuil/azure-devops-gitleaks#37]
Hi, I have tried all scanmodes and configfiles and yet to come up with a way to scan all folders and files in an azure devops repository. What am I missing? How can scan a whole repo using the - task: Gitleaks@2 in azure pipelines.
Regards

**Comment by JoostVoskuil** [comment]
Hi @Sageatahan I am not understanding this.
The scanlocation is set to the root of your repository (Build.SourcesDirectory) so it is scanning the repository (after checkout).

**Comment by JoostVoskuil** [comment]
So what is the issue? That not all your secrets are found?

Gitleaks detects secrets based on regexp. It is based on certain rules.

**Comment by JoostVoskuil** [comment]
I am sorry but I don't understand what you want me to do

**Comment by JoostVoskuil** [comment]
Closed because of no clear understanding of issue/reproduction steps
