### ISSUE TITLE
GitLeaks Task Failed getting Local issuer Certificate on Windows Agent

### ISSUE THREAD

**Issue by cliftonz1** [JoostVoskuil/azure-devops-gitleaks#39]
We have an agent set up to connect to out through our corporate proxy and we are seeing this issue when trying to run Gitleaks.

''' ##[error]unable to get local issuer certificate```

Any help is appreciated.

**Comment by JoostVoskuil** [comment]
Hi @cliftonz1 yes, never tested it with a proxy, so I can imagine it has bugs. Can you run the task with a variable called _system.debug_ and set the value to _true_?

Then please copy/paste the log of the Gitleaks task fully. Thank you!

**Comment by JoostVoskuil** [comment]
Can you also provide me with what kind of proxy you are running? It seems that there is a certificate required. I see that the Gitleaks task works with basic proxy stuff. It takes the proxy settings from the agent.

**Comment by JoostVoskuil** [comment]
@cliftonz1 ?

**Comment by cliftonz1** [comment]
@JoostVoskuil  Sorry for the late reply.
We use NetScaler for this issue. 
I have also opened a ticket with Microsoft and will update this thread accordingly.

**Comment by JoostVoskuil** [comment]
Hiu @cliftonz1 sorry but I don't understand you. Do you have this issue also for other tasks or only Gitleaks?

**Comment by cliftonz1** [comment]
I updated the last comment,
I am only seeing this issue on Gitleaks, however I am unsure if this is a Gitleaks issue or an agent issue.

**Comment by JoostVoskuil** [comment]
So what does Microsoft has to do with it?

Can you provide me with the requested information?
