### ISSUE TITLE
Folder Exclusion

### ISSUE THREAD

**Issue by alexandrelimait** [JoostVoskuil/azure-devops-gitleaks#4]
I would like to request if it would be possible to develop a field for exceptions of folders to be scanned, or if there is some workaround for how to do it.

**Comment by JoostVoskuil** [comment]
I am not sure why you want to use this. Can you ellaborate?
Why you want to have one folder that might contains secrets while another one is scanned?

**Comment by alexandrelimait** [comment]
During my build pipeline, I have a task to npm install and it generates the node_modules folder when gitleaks run over the repository it detects some hashes inside the node modules, but theses hashed from node_modules, are not secrets related to my business, that why I want to exclude the folder node_modules

**Comment by JoostVoskuil** [comment]
And what if gitleaks is run before the npm install?

**Comment by alexandrelimait** [comment]
yes, I did and worked, maybe a suggestion for a future feature ;)
