### ISSUE TITLE
Gitleaks pipeline failing with error on Windows agents

### ISSUE THREAD

**Issue by mi-matic** [JoostVoskuil/azure-devops-gitleaks#47]
We are experiencing issues with Gitleaks pipeline which is failing with ERR Failed to locate unzip command '/usr/bin/unzip'! although this is running on Windows agent.

If we run this same pipeline on Linux agent it finish without errors and works fine.

This is example of run on Windows agent:

Starting: Gitleaks

Task         : Gitleaks scan
Description  : Scan git repos (or files) for secrets using regex and entropy.
Version      : 2.2.30
Author       : Joost Voskuil (joost@foxhole.nl)
Help         : [More information](https://github.com/JoostVoskuil/azure-devops-gitleaks)

Thanks to Zachary Rice (https://github.com/zricethezav) for creating and maintaining gitleaks.
Thanks to Jesse Houwing (https://github.com/jessehouwing) for providing a gitleaks config that has most of Microsoft's deprecated credscan rules ported to it.

The latest version of the tool is available in the toolcache. Version is 8.9.0
Found tool in cache: gitleaks 8.9.0 x64
C:\hostedtoolcache\windows\gitleaks\8.9.0\x64\gitleaks.exe detect --config=./GitLeaks/GitLeaks.toml --source=F:\build\autobv.9\35\s --redact --report-format=sarif --report-path=F:\build\autobv.9\_temp\gitleaks-report-12f1170f-54f2-53f3-20dd-22fc7dff55f9.sarif

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

8:26AM ERR Failed to locate unzip command '/usr/bin/unzip'!
8:26AM ERR Failed to locate unzip command '/usr/bin/unzip'!
8:26AM ERR Failed to locate unzip command '/usr/bin/unzip'!
8:28AM ERR Failed to locate unzip command '/usr/bin/unzip'!
##[error]See https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository for information how to remove secrets.
##[warning]Secrets found or error encountered when running Gitleaks. See log and report for details.
Finishing: Gitleaks

And this is how our task is configured:

- task: Gitleaks@2
  inputs:
    scanlocation: '$(Build.SourcesDirectory)'
    configtype: 'custom'
    configfile: ./GitLeaks/GitLeaks.toml
    uploadresults: true
    reportformat: 'sarif'
    scanmode: all
    taskfail: false

Strange thing is that this error appears only when scanmode is set to all, if it's set to prevalidation and run for PR it goes through without errors on Windows agents.

Starting: Gitleaks

Task         : Gitleaks scan
Description  : Scan git repos (or files) for secrets using regex and entropy.
Version      : 2.2.30
Author       : Joost Voskuil (joost@foxhole.nl)
Help         : [More information](https://github.com/JoostVoskuil/azure-devops-gitleaks)

Thanks to Zachary Rice (https://github.com/zricethezav) for creating and maintaining gitleaks.
Thanks to Jesse Houwing (https://github.com/jessehouwing) for providing a gitleaks config that has most of Microsoft's deprecated credscan rules ported to it.

Only commits belonging to this Pull Request are scanned.
Scanning for 29 Git commit(s) for this build. First commit is 62322a1ee0b829, Last commit is fc75d133b48
The latest version of the tool is available in the toolcache. Version is 8.9.0
Found tool in cache: gitleaks 8.9.0 x64
C:\hostedtoolcache\windows\gitleaks\8.9.0\x64\gitleaks.exe detect --config=./GitLeaks/GitLeaks.toml --source=F:\build\autobv.3\221\s/src/Services/Functions/Reporting/ReportingFunction "--log-opts=62322a1ee0b829^! fc75d133b48" --redact --report-format=sarif --report-path=F:\build\autobv.3\_temp\gitleaks-report-041a692d-d80f-5a06-0b64-9e4539023300.sarif

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

8:04AM INF scan completed in 190.5997ms
8:04AM INF no leaks found
Finishing: Gitleaks

**Comment by JoostVoskuil** [comment]
Hi @mi-matic ,

This is strange, since gitleaks seems to be already in the tool cache, so no idea what is there to unzip.

Are you running on self-hosted agents or on the Microsoft hosted agents?
Can you run the pipeline with the variable system.debug set to true and can you send me the log?

**Comment by mi-matic** [comment]
Hi @JoostVoskuil ,

We are running self-hosted agents and below is pipeline debug output

##[debug]Evaluating condition for step: 'Gitleaks'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Gitleaks
==============================================================================
Task         : Gitleaks scan
Description  : Scan git repos (or files) for secrets using regex and entropy.
Version      : 2.2.30
Author       : Joost Voskuil (joost@foxhole.nl)
Help         : [More information](https://github.com/JoostVoskuil/azure-devops-gitleaks)
==============================================================================
##[debug]Using node path: C:\Agents\b.1\externals\node10\bin\node.exe
##[debug]agent.TempDirectory=F:\build\b.1\_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_CONFIGFILE
##[debug]loading INPUT_CONFIGTYPE
##[debug]loading INPUT_PREDEFINEDCONFIGFILE
##[debug]loading INPUT_REDACT
##[debug]loading INPUT_REPORTFORMAT
##[debug]loading INPUT_SCANLOCATION
##[debug]loading INPUT_SCANMODE
##[debug]loading INPUT_TASKFAIL
##[debug]loading INPUT_TASKFAILONEXECUTIONERROR
##[debug]loading INPUT_UPLOADRESULTS
##[debug]loading INPUT_VERBOSE
##[debug]loading INPUT_VERSION
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loaded 16
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]check path : F:\build\b.1\_tasks\Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119\2.2.30\task.json
##[debug]adding resource file: F:\build\b.1\_tasks\Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119\2.2.30\task.json
##[debug]system.culture=en-US
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]check path : F:\build\b.1\_tasks\Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119\2.2.30\node_modules\azure-pipelines-tool-lib\lib.json
##[debug]adding resource file: F:\build\b.1\_tasks\Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119\2.2.30\node_modules\azure-pipelines-tool-lib\lib.json
##[debug]system.culture=en-US
##[debug]Resource file has already set to: F:\build\b.1\_tasks\Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119\2.2.30\task.json
Thanks to Zachary Rice (https://github.com/zricethezav) for creating and maintaining gitleaks.
Thanks to Jesse Houwing (https://github.com/jessehouwing) for providing a gitleaks config that has most of Microsoft's deprecated credscan rules ported to it.

##[debug]scanlocation=F:\build\b.1\79\s
##[debug]reportformat=sarif
##[debug]reportname=undefined
##[debug]system.debug=True
##[debug]Agent.TempDirectory=F:\build\b.1\_temp
##[debug]System.JobId=12f1170f-54f2-53f3-20dd-22fc7dff55f9
##[debug]scanmode=all
##[debug]Build.Reason=Manual
##[warning]Secrets found or error encountered when running Gitleaks. See log and report for details.
##[debug]Processed: ##vso[task.issue type=warning;]Secrets found or error encountered when running Gitleaks. See log and report for details.
##[debug]Processed: ##vso[task.complete result=SucceededWithIssues;]Secrets found or error encountered when running Gitleaks. See log and report for details.
Finishing: Gitleaks

**Comment by JoostVoskuil** [comment]
Hi @mi-matic, it is misterious. However I found a bug that the extension is not downloading the latest version of gitleaks. Wil solve this this weekend.

Can you try running gitleaks with input:
version: '8.12.0'

**Comment by mi-matic** [comment]
Hi @JoostVoskuil, there is a change when version is set to '8.12.0' but error is still showing although some scan results are there.
Also I can see Linux commands in the log like rm -rf which isn't a valid one in Powershell.

##[debug]Evaluating condition for step: 'Gitleaks'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Gitleaks
==============================================================================
Task         : Gitleaks scan
Description  : Scan git repos (or files) for secrets using regex and entropy.
Version      : 2.2.30
Author       : Joost Voskuil (joost@foxhole.nl)
Help         : [More information](https://github.com/JoostVoskuil/azure-devops-gitleaks)
==============================================================================
##[debug]Using node path: C:\Agents\autobv.4\externals\node10\bin\node.exe
##[debug]agent.TempDirectory=F:\build\autobv.4\_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_CONFIGFILE
##[debug]loading INPUT_CONFIGTYPE
##[debug]loading INPUT_PREDEFINEDCONFIGFILE
##[debug]loading INPUT_REDACT
##[debug]loading INPUT_REPORTFORMAT
##[debug]loading INPUT_SCANLOCATION
##[debug]loading INPUT_SCANMODE
##[debug]loading INPUT_TASKFAIL
##[debug]loading INPUT_TASKFAILONEXECUTIONERROR
##[debug]loading INPUT_UPLOADRESULTS
##[debug]loading INPUT_VERBOSE
##[debug]loading INPUT_VERSION
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loaded 16
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]check path : F:\build\autobv.4\_tasks\Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119\2.2.30\task.json
##[debug]adding resource file: F:\build\autobv.4\_tasks\Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119\2.2.30\task.json
##[debug]system.culture=en-US
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]check path : F:\build\autobv.4\_tasks\Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119\2.2.30\node_modules\azure-pipelines-tool-lib\lib.json
##[debug]adding resource file: F:\build\autobv.4\_tasks\Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119\2.2.30\node_modules\azure-pipelines-tool-lib\lib.json
##[debug]system.culture=en-US
##[debug]Resource file has already set to: F:\build\autobv.4\_tasks\Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119\2.2.30\task.json
Thanks to Zachary Rice (https://github.com/zricethezav) for creating and maintaining gitleaks.
Thanks to Jesse Houwing (https://github.com/jessehouwing) for providing a gitleaks config that has most of Microsoft's deprecated credscan rules ported to it.

##[debug]scanlocation=F:\build\autobv.4\44\s
##[debug]reportformat=sarif
##[debug]reportname=undefined
##[debug]system.debug=True
##[debug]Agent.TempDirectory=F:\build\autobv.4\_temp
##[debug]System.JobId=12f1170f-54f2-53f3-20dd-22fc7dff55f9
##[debug]scanmode=all
##[debug]Build.Reason=Manual
##[debug]Resource file has already set to: F:\build\autobv.4\_tasks\Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119\2.2.30\task.json
##[debug]version=8.12.0
##[debug]customtoollocation=undefined
##[debug]Agent.ProxyUrl=undefined
##[debug]cleaning: 8.12.0
##[debug]Agent.OS=Windows_NT
##[debug]Agent.Version=2.209.0
##[debug]Agent.ToolsDirectory=C:/hostedtoolcache/windows
##[debug]isExplicit: 8.9.0
##[debug]explicit? true
##[debug]Cached versions of Gitleaks on the agent are: 8.9.0
##[debug]cleaning: 8.12.0
Version 8.12.0 is not available in toolcache. Downloading version 8.12.0.
##[debug]cleaning: 8.12.0
##[debug]Agent.OS=Windows_NT
##[debug]Agent.OSArchitecture=X64
##[debug]
##[debug]Agent.Version=2.209.0
##[debug]Agent.TempDirectory=F:\build\autobv.4\_temp
##[debug]testing directory 'F:\build\autobv.4\_temp'
Downloading: https://github.com/zricethezav/gitleaks/releases/download/v8.12.0/gitleaks_8.12.0_windows_x64.zip
##[debug]destination F:\build\autobv.4\_temp\e6248cdd-9aba-4369-99c8-9ef236c220bb
##[debug]downloading
##[debug]Content-Length of downloaded file: 2750158
##[debug]creating stream
##[debug]download complete
##[debug]Downloaded file size: 2750158 bytes
##[debug]Downloading https://github.com/zricethezav/gitleaks/releases/download/v8.12.0/gitleaks_8.12.0_windows_x64.zip
##[debug]Agent.OS=Windows_NT
Extracting archive
##[debug]Agent.Version=2.209.0
##[debug]Agent.TempDirectory=F:\build\autobv.4\_temp
##[debug]testing directory 'F:\build\autobv.4\_temp\83be8180-65db-43f1-b626-c41045864c57'
##[debug]testing directory 'F:\build\autobv.4\_temp'
##[debug]mkdir 'F:\build\autobv.4\_temp\83be8180-65db-43f1-b626-c41045864c57'
##[debug]which 'C:\windows\system32\chcp.com'
##[debug]found: 'C:\windows\system32\chcp.com'
##[debug]C:\windows\system32\chcp.com arg: 65001
##[debug]C:\windows\system32\chcp.com arg: 65001
##[debug]exec tool: C:\windows\system32\chcp.com
##[debug]exec tool: C:\windows\system32\chcp.com
##[debug]arguments:
##[debug]arguments:
##[debug]   65001
##[debug]   65001
C:\windows\system32\chcp.com 65001
Active code page: 65001
##[debug]Exit code 0 received from tool 'C:\windows\system32\chcp.com'
##[debug]Exit code 0 received from tool 'C:\windows\system32\chcp.com'
##[debug]STDIO streams have closed for tool 'C:\windows\system32\chcp.com'
##[debug]STDIO streams have closed for tool 'C:\windows\system32\chcp.com'
##[debug]which 'powershell'
##[debug]found: 'C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe arg: -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command
##[debug]C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe arg: $ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('F:\build\autobv.4\_temp\e6248cdd-9aba-4369-99c8-9ef236c220bb', 'F:\build\autobv.4\_temp\83be8180-65db-43f1-b626-c41045864c57')
##[debug]exec tool: C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
##[debug]arguments:
##[debug]   -NoLogo
##[debug]   -Sta
##[debug]   -NoProfile
##[debug]   -NonInteractive
##[debug]   -ExecutionPolicy
##[debug]   Unrestricted
##[debug]   -Command
##[debug]   $ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('F:\build\autobv.4\_temp\e6248cdd-9aba-4369-99c8-9ef236c220bb', 'F:\build\autobv.4\_temp\83be8180-65db-43f1-b626-c41045864c57')
C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('F:\build\autobv.4\_temp\e6248cdd-9aba-4369-99c8-9ef236c220bb', 'F:\build\autobv.4\_temp\83be8180-65db-43f1-b626-c41045864c57')"
##[debug]Exit code 0 received from tool 'C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]STDIO streams have closed for tool 'C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]Agent.OS=Windows_NT
##[debug]Agent.OS=Windows_NT
Caching tool: gitleaks 8.12.0 x64
##[debug]source file:F:\build\autobv.4\_temp\83be8180-65db-43f1-b626-c41045864c57\gitleaks.exe
##[debug]Agent.Version=2.209.0
##[debug]Agent.ToolsDirectory=C:/hostedtoolcache/windows
##[debug]destination C:\hostedtoolcache\windows\gitleaks\8.12.0\x64
##[debug]rm -rf C:\hostedtoolcache\windows\gitleaks\8.12.0\x64
##[debug]rm -rf C:\hostedtoolcache\windows\gitleaks\8.12.0\x64.complete
##[debug]testing directory 'C:\hostedtoolcache\windows\gitleaks\8.12.0\x64'
##[debug]testing directory 'C:\hostedtoolcache\windows\gitleaks\8.12.0'
##[debug]testing directory 'C:\hostedtoolcache\windows\gitleaks'
##[debug]mkdir 'C:\hostedtoolcache\windows\gitleaks\8.12.0'
##[debug]mkdir 'C:\hostedtoolcache\windows\gitleaks\8.12.0\x64'
##[debug]destination fileC:\hostedtoolcache\windows\gitleaks\8.12.0\x64\gitleaks.exe
##[debug]Agent.Version=2.209.0
##[debug]Agent.ToolsDirectory=C:/hostedtoolcache/windows
##[debug]finished caching tool
##[debug]Agent.OS=Windows_NT
##[debug]cachedToolExecutable: C:\hostedtoolcache\windows\gitleaks\8.12.0\x64\gitleaks.exe
##[debug]Agent.OS=Windows_NT
##[debug]which 'C:\hostedtoolcache\windows\gitleaks\8.12.0\x64\gitleaks.exe'
##[debug]found: 'C:\hostedtoolcache\windows\gitleaks\8.12.0\x64\gitleaks.exe'
##[debug]configtype=custom
##[debug]predefinedconfigfile=GitleaksUdmCombo.toml
##[debug]configfile=./GitLeaks/GitLeaks.toml
##[debug]configtype=custom
##[debug]predefinedconfigfile=GitleaksUdmCombo.toml
##[debug]configfile=./GitLeaks/GitLeaks.toml
##[debug]redact=true
##[debug]verbose=false
C:\hostedtoolcache\windows\gitleaks\8.12.0\x64\gitleaks.exe detect --config=./GitLeaks/GitLeaks.toml --source=F:\build\autobv.4\44\s --redact --report-format=sarif --report-path=F:\build\autobv.4\_temp\gitleaks-report-12f1170f-54f2-53f3-20dd-22fc7dff55f9.sarif

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

7:56AM ERR [git] Failed to locate unzip command '/usr/bin/unzip'!
7:56AM ERR [git] Failed to locate unzip command '/usr/bin/unzip'!
7:57AM ERR [git] Failed to locate unzip command '/usr/bin/unzip'!
7:58AM ERR [git] Failed to locate unzip command '/usr/bin/unzip'!
7:58AM ERR git error encountered, see logs
7:58AM WRN partial scan completed in 2m12s
7:58AM WRN 16 leaks found in partial scan
##[debug]taskfail=false
##[debug]uploadresults=true
##[debug]Uploading report file to CodeAnalysisLogs
##[debug]Upload artifact: F:\build\autobv.4\_temp\gitleaks-report-12f1170f-54f2-53f3-20dd-22fc7dff55f9.sarif to server for build: 162642 at backend.
##[debug]Processed: ##vso[artifact.upload containerfolder=Gitleaks;artifactname=CodeAnalysisLogs;]F:\build\autobv.4\_temp\gitleaks-report-12f1170f-54f2-53f3-20dd-22fc7dff55f9.sarif
##[error]See https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository for information how to remove secrets.
##[debug]Processed: ##vso[task.issue type=error;]See https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository for information how to remove secrets.
##[debug]task result: SucceededWithIssues
##[warning]Secrets found or error encountered when running Gitleaks. See log and report for details.
##[debug]Processed: ##vso[task.issue type=warning;]Secrets found or error encountered when running Gitleaks. See log and report for details.
##[debug]Processed: ##vso[task.complete result=SucceededWithIssues;]Secrets found or error encountered when running Gitleaks. See log and report for details.
Async Command Start: Upload Artifact
Uploading 1 files
##[debug]File: 'F:\build\autobv.4\_temp\gitleaks-report-12f1170f-54f2-53f3-20dd-22fc7dff55f9.sarif' took 334 milliseconds to finish upload
##[debug]Detail upload trace for file: Gitleaks/gitleaks-report-12f1170f-54f2-53f3-20dd-22fc7dff55f9.sarif
##[debug]File 'Gitleaks/gitleaks-report-12f1170f-54f2-53f3-20dd-22fc7dff55f9.sarif' will be uploaded in one chunk.
##[debug]Attempt '1' for uploading chunk '1' of file 'Gitleaks/gitleaks-report-12f1170f-54f2-53f3-20dd-22fc7dff55f9.sarif'.
##[debug]Generate new HttpRequest for uploading file 'Gitleaks/gitleaks-report-12f1170f-54f2-53f3-20dd-22fc7dff55f9.sarif', chunk '1' of '1'.
##[debug]Start uploading file 'Gitleaks/gitleaks-report-12f1170f-54f2-53f3-20dd-22fc7dff55f9.sarif' to server, chunk '1'.
##[debug]Finished upload chunk '1' of file 'Gitleaks/gitleaks-report-12f1170f-54f2-53f3-20dd-22fc7dff55f9.sarif', elapsed 275 (ms), response code 'Created'.
File upload succeed.
Upload 'F:\build\autobv.4\_temp\gitleaks-report-12f1170f-54f2-53f3-20dd-22fc7dff55f9.sarif' to file container: '#/16985867/Gitleaks'
Associated artifact 137808 with build 162642
Async Command End: Upload Artifact
Finishing: Gitleaks

**Comment by JoostVoskuil** [comment]
Hi @mi-matic for me it is clear now that the _ERR [git] Failed to locate unzip command '/usr/bin/unzip'!_ errors are the output of gitleaks itself and not the Azure DevOps extension.

Can you do a git clone of the repo and use gitleaks to scan it manually? It should give the same output.  Do you have zip files in your repo?

**Comment by jessehouwing** [comment]
Since this is a private agent, I suspect that tools that gitleaks requires
aren't installed on the agent or aren't part of the path.

I also see what seems like a VERY old PowerShell version being used to  run
a few things.

I suspect gitleaks requires gitbash for windows to be installed and for the
Linux tools to be registered in the path.

I haven't tested this hypothesis, but it would make sense given the error
messages.

Not sure if there is a binary for gitleaks that contains a minimal Linux
shell environment or whether you could be able to acquire one through a
tool installer.

To test this hypothesis, install git for windows on the agent and make sure
to register the Unix tools in the path. Make sure you add these paths to
the global windows environment to make sure there changes are available to
the user running the agent. Then restart the agent.

**Comment by JoostVoskuil** [comment]
Just tested this and I can confirm. You need git for Windows on the agent + Unix tools.
