### ISSUE TITLE
scanmode: 'all' does not identify secrets from historic commits

### ISSUE THREAD

**Issue by meeragirijan** [JoostVoskuil/azure-devops-gitleaks#53]
I'm implementing gitleaks as cred scanner alternative in a DevOps pipeline using YAML.
Trying out scanmode 'all' option on a feature branch with multiple commits, the runs seem to only detect the current state of the branch and not previous commits. What is the expected behavior, is any additional settings that I'm missing?

**Comment by JoostVoskuil** [comment]
Hi @meeragirijan, can you provide the output of the console of Azure DevOps?
When scanmode is set to 'all', all the commits should be scanned.

**Comment by JoostVoskuil** [comment]
If you set this in your pipeline, all the commits are retreived:

steps:
- fetchDepth: 0

**Comment by meeragirijan** [comment]
Thank you!!

**Comment by meeragirijan** [comment]
@JoostVoskuil  That seems to have resolved the issue it is now scanning all the commits. 
FetchDepth was set as part of the checkout step and it behaves as expected. Thank you for the quick help! :)
