### ISSUE TITLE
Editing the [allowlist] to allow certain regexes is not eliminating these from being detected

### ISSUE THREAD

**Issue by meeragirijan** [JoostVoskuil/azure-devops-gitleaks#55]
Hi,

I'm trying to use a custom configuration file to identify guid as part of the secrets exposed however trying to allow certain occurrences of the guid in certain files we configured the allowlist to whitelist these; However these are still being identified as the substring contains the guid. How is the allowlist configured to work. Following are the snippet of regex and values we are working with. 

Regex for the allowlist : 
```
[allowlist]
description = "global allow lists"
regexes = ['''(?im)^\t\t@schedule_uid([\s|']|[\s|"]|[=]|)N'[{(]?[0-9A-F]{8}[-]?(?:[0-9A-F]{4}[-]?){3}[0-9A-F]{12}[)}]?([\s|'])'''
```
Sample for the allowlist: **		@schedule_uid=N'<GUID>'**
Rule for GUID:

```
[[rules]]
id = "CUSTOM-02" 
description = "GUID Rule" 
path = '''\.(?:xml|pubxml|definitions|ps1|wadcfgx|ccf|config|cscfg|json|js|txt|cpp|sql|md|java|FF|template|settings|ini|BF|ste|isml|test|ts|Azure|sample|backup|rd|hpp|psm1|cshtml|htm|bat|waz|yml|Beta|py|sh|m|php|xaml|keys|cmd|rds|loadtest|properties)$|hubot'''
regex = '''(?im)(?:[\s|']|[\s|"]|[=]|)[{(]?[0-9A-F]{8}[-](?:[0-9A-F]{4}[-]){3}[0-9A-F]{12}[)}]?'''
```

**Comment by JoostVoskuil** [comment]
Hi @meeragirijan ,

Your question is a Gitleaks question. I am not the maintainer on Gitleaks itself but only the extension. The best thing you can do is ask this question at the Gitleaks repo: https://github.com/zricethezav/gitleaks

**Comment by meeragirijan** [comment]
@JoostVoskuil  Thank you. Will post this there. Just an update I was using this on the devOps extension.
