### ISSUE TITLE
Im trying to add more options but whenever I repackage it gives an error

### ISSUE THREAD

**Issue by yuen07** [JoostVoskuil/azure-devops-gitleaks#6]
So, im thinking to add more options into the code but whenever i download the source code and repackage with the command line " tfx extension create --manifest-globs vss-extension.json" it creates me a new plugin, i tried to run this on my dev and its giving me an error saying it cant find the inde.js file, have you experience this? 
error after installing the "new plugin"
##[error]File not found: '/home/vsts/work/_tasks/Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119/1.1.0/index.js'

when I install the plugin from the marketplace it doesnt give this error

**Comment by JoostVoskuil** [comment]
I find this all really strange. You are violating the MIT license. You have forked my code and removed my name as the author and replaced it with yours.

**Comment by yuen07** [comment]
Dude, look I am going to say it again, it was a honest mistake, if you look at my fork code, you will find that your name is still on the readme file, still on the task files, the full description is saying you and your project are the main authors, I'm just extending it, is not like I removed your entire name/repo out of the fork, you can literally see this here:
***@***.***

Also here ""description": "Scan git repos (or files) for secrets using regex and entropy. This is a fork from Joost Voskuil https://github.com/JoostVoskuil/azure-devops-gitleaks""

Like I mention before, I was playing with the plugin and mistakenly uploaded publicly, im have been working on a private version for the last two days screenshot here:
***@***.***

And also requested for Azure marketplace to delete this current Public plugin, here is another screenshot
***@***.***


For real, it was just an honest mistake.


Yuen

**Comment by yuen07** [comment]
I sent you a full email via email describing what happen and screenshots of the mistakes and stuff, plz review it, as mention before, it was a honest mistake.
