### ISSUE TITLE
Additional config feature for separate whitelist file  for  different project in an organisation 

### ISSUE THREAD

**Issue by Sneha2610** [JoostVoskuil/azure-devops-gitleaks#62]
Hi team, 
I am trying to pass multiple whitelist file under gitleaks task not within gitleaks.toml. i believe we use 
--additional config in gitleaks7 in normal cli. Is there any option to pass it same like in azure devops task1. Please help

**Comment by JoostVoskuil** [comment]
Hi @Sneha2610,

Gitleaks 8 does not support a whitelist file from my understanding. See https://github.com/zricethezav/gitleaks
You might add a .gitleaksignore to your repo.

**Comment by JoostVoskuil** [comment]
Hi @Sneha2610 does this answer your question?

**Comment by JoostVoskuil** [comment]
Clossed, no response
