### ISSUE TITLE
Handling Detected Secrets in Pipelines: Preventing Failures in Certain Scenarios

### ISSUE THREAD

**Issue by LTomer** [JoostVoskuil/azure-devops-gitleaks#65]
Hi,

I have configured a task in my build pipeline not to fail in case it detects a secret. However, when the task does detect a secret in the source control, it displays an error message that directs me to a documentation page for removing sensitive data from a repository (HelpOnSecretsFound).

This failed message will appear in the source control history under status, which may confuse others who see it. Because the pipeline is set to enforce certain policies for a branch, it may appear to others that the build process has failed even though the task did not actually cause the pipeline to fail.

**Comment by JoostVoskuil** [comment]
Hi @LTomer can you check if your issue is solved now? You are right, there was a bug in the reporting.

**Comment by LTomer** [comment]
Hi,

Thank you for the quick response.
After this fix, the task ended with SucceededWithIssues without any error message - the expected result.

When I open the source control history, I still get the failed message - it's probably something related to the Azure DevOps platform and pipeline that completes with SucceededWithIssues displayed as failed.
