### ISSUE TITLE
PR build doesn't show any results in ADO pipeline under scan tabs

### ISSUE THREAD

**Issue by AshishDadhich4h2** [JoostVoskuil/azure-devops-gitleaks#67]
I am using folloiwng tasks in ADO pipeline. It works fine and publish the SAIRF test results under Scans tab  with branch build but same thing doesn't work for PR build.
- task: Gitleaks@2
     displayName: "Scan secrets > Gitleaks"
     inputs:
        scanlocation: '$(workdir)'
        configtype: 'predefined'
        predefinedconfigfile: 'GitleaksUdmCombo.toml'
        reportformat: 'sarif'
        taskfail: false # true Fail the task if secrets are found
        verbose: true

Branch build pipeline output
![image](https://github.com/JoostVoskuil/azure-devops-gitleaks/assets/37674243/42128e25-7c09-4829-bb8b-aa86e56533ce)

PR build pipeline output 

![image](https://github.com/JoostVoskuil/azure-devops-gitleaks/assets/37674243/0c86dbda-7d4a-4f44-b05a-859dcd54682c)

Please suggest.

**Comment by AshishDadhich4h2** [comment]
So, after checking logs it shows:
`Only commits belonging to this Pull Request are scanned.`
When we run gitleaks on branch level it scans all the commits and code but for PR branch/build it scans only PR commit.

**Comment by JoostVoskuil** [comment]
Can you tell me what you expect and what you get?

Also check the readme and check the scanmode:

all' will scan all commits.
'prevalidation' will scan only the commits that are part of a Pull Request.
'changes' will scan only the changes between this build and the previous build.
'smart' will detect the best scanmode.
'nogit' will run GitLeaks in no-git mode (flat file scan).
'custom' will allow you to provide custom -log-opts.

**Comment by AshishDadhich4h2** [comment]
@JoostVoskuil  Thank you !!! yeah scanall : 'all' worked and published all the results.
Thank you again !
