### ISSUE TITLE
It reports .cer as a secret in failed test results. Is .cer file a secret?

### ISSUE THREAD

**Issue by AshishDadhich4h2** [JoostVoskuil/azure-devops-gitleaks#68]
After running this task in ADO pipeline , it scans .cer files as as secert and reports as a failed test.

Just wanted to understand why it's so.

**Comment by jessehouwing** [comment]
These were ported from the creds an utility (rule id = "CSCAN0020") which does detect files that contain a certificate.

Credscan contains some additional logic to decode the certificate to see if the private key is included in the file. Gitleaks doesn't support these additional parsers, so this rule is more likely to cause false positives in gitleaks than in the original credscan version of the rule.

**Comment by AshishDadhich4h2** [comment]
Thank you for replying and clarification!
