### ISSUE TITLE
Uploading results in ADO fails with error when the CodeAnalysisLogs artifact already exists

### ISSUE THREAD

**Issue by huntantr** [JoostVoskuil/azure-devops-gitleaks#69]
I am already using the [SARIF viewer extension](https://marketplace.visualstudio.com/items?itemName=sariftools.scans) in other parts of my build. When GitLeaks trying to upload the report it fails with the following error.
##[error]Artifact CodeAnalysisLogs already exists for build ####

This should upload even if it already exists.

**Comment by JoostVoskuil** [comment]
Hi @huntantr did you add Gitleaks twice in your job?

**Comment by JoostVoskuil** [comment]
CodeAnalysisLogs is the name of the artifact so it almost seems that the error is correct and it is not something related to this task. Can you swap places in your pipeline and run the Gitleaks task first? I think the other task will then fail.

**Comment by huntantr** [comment]
I have multiple custom steps that create sarif files that are added to the CodeAnalysisLogs container. Playing around with step sequences to see if this helps.
