### ISSUE TITLE
The generic-api-key rule should ignore "PublicKeyToken" in web.config files

### ISSUE THREAD

**Issue by frankvaneykelen-work** [JoostVoskuil/azure-devops-gitleaks#72]
This line from a `web.config` file is incorrectly flagged by generic-api-key as containing secrets:

```xml
<section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
```

When I run the scan with `redact: false` it displays "b77a5c561934e089" as secret.

Strangely enough it does not flag any of the other 59 occurrences of `PublicKeyToken` as a secret. Some examples of other lines (that are before the line shown above):

```xml
<sectionGroup name="system.web.webPages.razor" type="System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35">
  <section name="host" type="System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" requirePermission="false" />
  <section name="pages" type="System.Web.WebPages.Razor.Configuration.RazorPagesSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" requirePermission="false" />
</sectionGroup>
```

The Generic API Key rule is in the GitleaksUdmCombo.toml file.

**Comment by JoostVoskuil** [comment]
Hi @frankvaneykelen-work, the Azure DevOps extension is just a wrapper around GitLeaks. I think your issue is related to the config files of Gitleaks itself. The combo file is merged by me however the basic configuration is provided by Gitleaks itself. Can you file your issue at https://github.com/gitleaks/gitleaks?

**Comment by frankvaneykelen-work** [comment]
Thanks, I found an existing issue there, and added my example there: https://github.com/gitleaks/gitleaks/issues/1052
