### ISSUE TITLE
Add option to include baseline file

### ISSUE THREAD

**Issue by mobijmartinez** [JoostVoskuil/azure-devops-gitleaks#73]
When working directly with gitleaks it is possible to add a baseline file that contains all the secrets that have been acknowledged and should be ignored (https://github.com/gitleaks/gitleaks/tree/master#creating-a-baseline). Would be great to add support for setting this file within the task configuration.

**Comment by JoostVoskuil** [comment]
Hi @mobijmartinez, I've just added this option
