### ISSUE TITLE
taskFail Query

### ISSUE THREAD

**Issue by ChrisHolman** [JoostVoskuil/azure-devops-gitleaks#76]
If taskFail is set to True, and issues are detected, the task fails. 

If taskFail is set to False, and issues are detected, the task presents a warning (!). 

Is there a way to remove this warning, so if issues are detected, and the toggle is set to false, the task will Pass?

**Comment by JoostVoskuil** [comment]
Hi @ChrisHolman can you elaborate? The pipeline job will get the status SucceededWithWarnings and not Fail.

What are you trying to achieve?

**Comment by ChrisHolman** [comment]
Looking to remove the SucceededWithWarnings flag. Although it may sound counter-intuitive, we would rather the task always passed, regardless of what was found, until we've managed to ascertain a baseline.

**Comment by JoostVoskuil** [comment]
SucceededWithWarnings is passed.

**Comment by JoostVoskuil** [comment]
Hi @ChrisHolman, I tought about it and I am not going to change the behavior. When secrets (either true secrets or false positives) there is a call for action. That call for action is either a warning or error. Suppressing both sounds an anti-pattern for me.
