### ISSUE TITLE
Enhancement request - provide the ability to choose the artifact name for uploading the results to AzureDevOps

### ISSUE THREAD

**Issue by daughey** [JoostVoskuil/azure-devops-gitleaks#78]
I would like the ability to choose the name of the artifact that the GitLeaks task uses when uploading the results to AzureDevOps.

There are two use cases where this is useful:
1. When a pipeline is performing multiple gitleaks scans across multiple repos.
1. When a re-run of a job/stage is performed and the gitleaks task has already uploaded

It's easy to work around by suppressing the upload and taking manual control of uploading with the publish task, but this task offers to do it for me so it would be nice to make use of that functionality.

**Comment by JoostVoskuil** [comment]
Hi @daughey I have added a reportartifactname parameter where you can steer the artifact name. Default remains CodeAnalysisLogs and is needed to make use of the 'Scans / SAST' tab. 

Together with the report name you can steer everything regarding multiple scans/re-runs
