### ISSUE TITLE
Document the output location

### ISSUE THREAD

**Issue by daughey** [JoostVoskuil/azure-devops-gitleaks#79]
The task outputs the report to the agent's temp directory `Agent.TempDirectory`.  This was worked out by observation and confirmed by reading the code (index.ts).

It would be useful if the output location of the report was mentioned in the README.md.  This is useful for situations where someone is taking control of publishing the output instead of letting the task do it for them.  In such a situation, the location of the output is important so it's helpful if it can be found more easily.

**Comment by JoostVoskuil** [comment]
Hi @daughey, I have added a reportfolder parameter where you can steer the output location.  Agent.TempDirectory is the default value.
