### ISSUE TITLE
Secrets not found with appsettings.json with ConnectionStrings

### ISSUE THREAD

**Issue by Wildav007** [JoostVoskuil/azure-devops-gitleaks#81]
Hi Joost

Sorry for contacting you like this but I have been struggling to get this to work for some time now. I tried connecting via LinkedIn but was unable.

I've tried every possible combination of settings but cannot get this to work.

I have resorted to running them all in one yaml file but the only failures I get are in a readme file that doesn't even belong to the solution.

If you could advise me, I'd really appreciate it.

Regards,
William
tech@williamdavies.info

trigger:
- dev

jobs:
- job: buildandtest
  
  pool:
    vmImage: ubuntu-latest

  variables:
    buildConfiguration: 'release'

  steps:
  - checkout: self
    fetchDepth: 0

  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages - dotnet restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
    
  - task: DotNetCoreCLI@2
    displayName: Build the project - dotnet build
    inputs:
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - script: |
      sudo apt update
      sudo apt install -y wget
      wget -qO gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.17.0/gitleaks_8.17.0_linux_x64.tar.gz
      tar -xvf gitleaks.tar.gz
      sudo mv gitleaks /usr/local/bin/
      rm gitleaks.tar.gz
      gitleaks detect --source=. --exit-code 126 --verbose --redact --report-format junit --report-path=$(Common.TestResultsDirectory)/gitleaks
    displayName: 'Detect Secrets - Gitleaks'
    continueOnError: true

  - task: Gitleaks@2
    displayName: Run GitLeaks scan - nogit
    inputs:
      scanlocation: '$(Build.SourcesDirectory)'
      configtype: 'predefined'
      predefinedconfigfile: 'GitleaksUdmCombo.toml'
      reportformat: 'json'
      scanmode: 'nogit'
      verbose: true
      taskfail: false
      version: latest
      
  - task: Gitleaks@2
    displayName: Run GitLeaks scan - all
    inputs:
      scanlocation: '$(Build.SourcesDirectory)'
      configtype: 'predefined'
      predefinedconfigfile: 'GitleaksUdmCombo.toml'
      reportformat: 'json'
      scanmode: 'all'
      verbose: true
      taskfail: false
      version: latest
      
  - task: Gitleaks@2
    displayName: Run GitLeaks scan - changes
    inputs:
      scanlocation: '$(Build.SourcesDirectory)'
      configtype: 'predefined'
      predefinedconfigfile: 'GitleaksUdmCombo.toml'
      reportformat: 'json'
      scanmode: 'changes'
      verbose: true
      taskfail: false
      version: latest
      
  - task: Gitleaks@2
    displayName: Run GitLeaks scan - smart
    inputs:
      scanlocation: '$(Build.SourcesDirectory)'
      configtype: 'predefined'
      predefinedconfigfile: 'GitleaksUdmCombo.toml'
      reportformat: 'json'
      scanmode: 'smart'
      verbose: true
      taskfail: false
      version: latest

**Comment by JoostVoskuil** [comment]
Hi @Wildav007 

Can you explain what the problem is?

**Comment by Wildav007** [comment]
Hi, yes, thank you so much for replying.

Essentially, it's not reporting any sensitive info in the repo but I have added things like the following to an appsettings.json file:


    "ConnectionStrings": {
      "DbConnString": "secret=password&password=secret"
    }

When I run it it just says no leaks found

**Comment by JoostVoskuil** [comment]
Hi @Wildav007,

You did nothing wrong. 

This (my code) is only a wrapper around gitleaks for Azure DevOps. So your issue actually belongs to https://github.com/gitleaks/gitleaks

However, I have looked at your example. There are two things:

1) Gitleaks is not that good in detecting secrets in json files. Because of that, your secrets remain undetected by the generic-api-rule. It should be detected by that because it contains the words password or secret.

2) Because your appsettings.json is not really the default way, the credscan rules also fail to detect the secrets.

You can file the issue at https://github.com/gitleaks/gitleaks, just mention your appsettings.json and that you expect that secrets should be detected.

Sorry, nothing I can do for you at the moment.

**Comment by Wildav007** [comment]
Thank you Joost, I appreciate you taking the time.
