### ISSUE TITLE
Featurerequest - Allow comments

### ISSUE THREAD

**Issue by anthraxn8b** [JoostVoskuil/azure-devops-gitleaks#83]
I just stumbled over the non existing comments.
Please add the feature like in gitignore where you can add a comment by just adding "#" at the beginning of the line.

**Comment by JoostVoskuil** [comment]
Hi @anthraxn8b I have no idea what you mean. Can you elaborate/give an example?

**Comment by anthraxn8b** [comment]
Sorry. Yes, a bit misleading.

I would like to add comments to the .gitleaksignore file.

In .gitignore this is done by just putting a # in front if the comment.

Maybe this could be done in the same way in .gitleaksignore...
