### ISSUE TITLE
Question: uploadresults

### ISSUE THREAD

**Issue by joaquin386** [JoostVoskuil/azure-devops-gitleaks#9]
Hi,

Thanks for adapting the tool to the AzureDevOps. I have set up "uploadresults: true" but then checking the artifact of the Build I dont see the report.

Where is the report uploaded on ADO? Can we send additional arguments like --react?

Thanks

Jo

**Comment by JoostVoskuil** [comment]
Hi @joaquin386 ,

When there are findings, there should be an json file uploaded as an artifact. When there are no findings, no artifact will be uploaded.

Can you check if this is the case?

Regards,

Joost

**Comment by joaquin386** [comment]
@JoostVoskuil Work as expected it is uploaded to the Build Artifacts.

The only thing missing is the --redact (just because the password will be shown plain text on the artifact)

**Comment by joaquin386** [comment]
I think the optional argument field to be pass to the command is better, just to allow people to add the options they like.

I agree redact (in my case) should be enable by default, but who knows .... somebody else will come and say the oposite, so thats the reason for an argument box where you can pass additional arguments as anyone likes.

**Comment by JoostVoskuil** [comment]
I've added the redact option as a boolean, defaults to false (since it needs to be provided to gitleaks)
I've also added a seperate extra argument textfield to provide other arguments to gitleaks.

Should fullfill your needs
