### ISSUE TITLE
Gitleaks version supported should be 8 and above

### ISSUE THREAD

**Issue by simply-me** [JoostVoskuil/azure-devops-gitleaks#91]
##[error]This version of the task only supports GitLeaks version 8. Specified version is 18.8.4

Specifying v18.8.4 and got the error above.

**Comment by JoostVoskuil** [comment]
You are specifing version 18?

**Comment by simply-me** [comment]
oops my mistake! should be 8.18.4.

**Comment by JoostVoskuil** [comment]
[like]  Joost Voskuil reacted to your message:
________________________________
